name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Add environment variables to .env
        run: |
          echo MONGO_DATABASE=${{ secrets.MONGO_DATABASE }} >> .env
          echo MONGO_URL=${{ secrets.MONGO_URL }} >> .env

      - name: Set environment variables
        run: |
          echo ::set-env name=MONGO_DATABASE::${{ secrets.MONGO_DATABASE }}
          echo ::set-env name=MONGO_URL::${{ secrets.MONGO_URL }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-$
          restore-keys: |
            poetry-$

      - name: Install Dependencies using Poetry
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run pytest
        run: poetry run python -m pytest -v
